### ISSUE TITLE
コンテナの停止/起動でファイルが初期化される

### ISSUE THREAD

**Issue by NaotoE0** [Bakudankun/docker-pukiwiki#1]
コンテナの起動、停止を行ったところ、pukiwiki.ini.phpなどのファイルが初期化されました。
entrypoint.shにおける下記記述に起因しているようです。
意図した挙動でなければ修正の検討をお願いします。

```bash
	if ! [ -e index.php -a -e wp-includes/version.php ]; then
```

**Comment by Bakudankun** [comment]
なんだこりゃ……済みません直します
報告ありがとうございます！
